
import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import style from './layout.module.css';

export const metadata: Metadata = {
  title: "한입 북스",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

    return (
        <html lang="kr">
        <body>
            <div className={style.container}>
                <header>
                    <Link href={'/'}>📚OneBite Books</Link>
                </header>
                <main>
                    {children}
                </main>
                <footer>
                    제작 @Kim
                </footer>
            </div>
        </body>
        </html>
    );
}